# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    # Enables the validator
    validation:
        email_validation_mode: html5

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # Assets versioning
    assets:
        # json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    # Translator (descomenta si usas traducciones)
    #translator:
    #    default_path: '%kernel.project_dir%/translations'
    #    fallbacks:
    #        - en
